version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo Pre-build started
  build:
    commands:
      - terraform init
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo Build completed
