version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install -y unzip
      - curl -LO https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
      - unzip terraform_0.12.24_linux_amd64.zip -d /usr/local/bin/
  pre_build:
    commands:
      - echo Pre-build started
  build:
    commands:
      - terraform init
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo Build completed
      - mkdir -p output
      - cp path/to/generated/file output/

artifacts:
  files:
    - '**/*'
  base-directory: 'output'
