version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib -v

  build:
    commands:
      - echo "Building application..."
      - python build_script.py

  post_build:
    commands:
      - echo "Packaging artifacts..."
      - zip -r myapp.zip .

artifacts:
  files:
    - myapp.zip
