version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install -y unzip
      - curl -LO https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
      - unzip terraform_0.12.24_linux_amd64.zip -d /usr/local/bin/
  pre_build:
    commands:
      - echo Pre-build started
      - ls -al  # List all files to verify the structure
  build:
    commands:
      - terraform init
      - terraform apply -auto-approve
      - ls -al  # List all files to verify the structure
  post_build:
    commands:
      - echo Build completed
      - mkdir -p output
      - cp /path/to/generated/file output/ || { echo "File not found"; exit 1; }  # Ensure the file exists before copying
      - ls -al output  # List the contents of the output directory

artifacts:
  files:
    - '**/*'
  base-directory: 'output'
