version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing Terraform"
      - curl -LO https://releases.hashicorp.com/terraform/1.0.6/terraform_1.0.6_linux_amd64.zip
      - unzip terraform_1.0.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo "Starting pre-build stage"
      - terraform --version
      - terraform init
  build:
    commands:
      - echo "Starting build stage"
      - terraform plan
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Starting post-build stage"
artifacts:
  files:
    - '**/*'
