version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Or any other runtime required
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
